export const BRAND_MAP = {
  acura:      { file: 'acura.js',       export: 'acuraData',       label: 'Acura' },
  alfa:       { file: 'alfa.js',        export: 'alfaData',        label: 'Alfa Romeo' },
  aston:      { file: 'aston.js',       export: 'astonData',       label: 'Aston Martin' },
  audi:       { file: 'audi.js',        export: 'audiData',        label: 'Audi' },
  aurus:      { file: 'aurus.js',       export: 'aurusData',       label: 'Aurus' },
  bentley:    { file: 'bentley.js',     export: 'bentleyData',     label: 'Bentley' },
  bmw:        { file: 'bmw.js',         export: 'bmwData',         label: 'BMW' },
  bugatti:    { file: 'bugatti.js',     export: 'bugattiData',     label: 'Bugatti' },
  buick:      { file: 'buick.js',       export: 'buickData',       label: 'Buick' },
  byd:        { file: 'byd.js',         export: 'bydData',         label: 'BYD' },
  cadillac:   { file: 'cadillac.js',    export: 'cadillacData',    label: 'Cadillac' },
  chery:      { file: 'chery.js',       export: 'cheryData',       label: 'Chery' },
  chevrolet:  { file: 'chevrolet.js',   export: 'chevroletData',   label: 'Chevrolet' },
  chrysler:   { file: 'chrysler.js',    export: 'chryslerData',    label: 'Chrysler' },
  citroen:    { file: 'citroen.js',     export: 'citroenData',     label: 'Citroën' },
  dacia:      { file: 'dacia.js',       export: 'daciaData',       label: 'Dacia' },
  daihatsu:   { file: 'daihatsu.js',    export: 'daihatsuData',    label: 'Daihatsu' },
  dodge:      { file: 'dodge.js',       export: 'dodgeData',       label: 'Dodge' },
  ford:       { file: 'ford.js',        export: 'fordData',        label: 'Ford' },
  honda:      { file: 'honda.js',       export: 'hondaData',       label: 'Honda' },
  hyundai:    { file: 'hyundai.js',     export: 'hyundaiData',     label: 'Hyundai' },
  infiniti:   { file: 'infinity.js',    export: 'infinitiData',    label: 'Infiniti' },
  jeep:       { file: 'jeep.js',        export: 'jeepData',        label: 'Jeep' },
  kia:        { file: 'kia.js',         export: 'kiaData',         label: 'Kia' },
  lada:       { file: 'lada.js',        export: 'ladaData',        label: 'Lada' },
  lambo:      { file: 'lambo.js',       export: 'lamboData',       label: 'Lamborghini' },
  lancia:     { file: 'lancia.js',      export: 'lanciaData',      label: 'Lancia' },
  lexus:      { file: 'lexus.js',       export: 'lexusData',       label: 'Lexus' },
  liauto:     { file: 'liauto.js',      export: 'liautoData',      label: 'Li Auto' },
  lincoln:    { file: 'lincoln.js',     export: 'lincolnData',     label: 'Lincoln' },
  lucid:      { file: 'lucid.js',       export: 'lucidData',       label: 'Lucid' },
  lynkco:     { file: 'lynkco.js',      export: 'lynkcoData',      label: 'Lynk & Co' },
  maserati:   { file: 'maserati.js',    export: 'maseratiData',    label: 'Maserati' },
  mazda:      { file: 'mazda.js',       export: 'mazdaData',       label: 'Mazda' },
  mclaren:    { file: 'mclaren.js',     export: 'mclarenData',     label: 'McLaren' },
  mers:       { file: 'mers.js',        export: 'mersData',        label: 'Mercedes-Benz' },
  mg:         { file: 'mg.js',          export: 'mgData',          label: 'MG' },
  mini:       { file: 'mini.js',        export: 'miniData',        label: 'MINI' },
  mits:       { file: 'mits.js',        export: 'mitsubishiData',  label: 'Mitsubishi' },
  moskvich:   { file: 'moskvich.js',    export: 'moskvichData',    label: 'Москвич' },
  nio:        { file: 'nio.js',         export: 'nioData',         label: 'NIO' },
  nissan:     { file: 'nissan.js',      export: 'nissanData',      label: 'Nissan' },
  opel:       { file: 'opel.js',        export: 'opelData',        label: 'Opel' },
  peugeot:    { file: 'peugeot.js',     export: 'peugeotData',     label: 'Peugeot' },
  pontiac:    { file: 'pontiac.js',     export: 'pontiacData',     label: 'Pontiac' },
  porsche:    { file: 'porsh.js',       export: 'porscheData',     label: 'Porsche' },
  ram:        { file: 'ram.js',         export: 'ramData',         label: 'RAM' },
  ranj:       { file: 'ranj.js',        export: 'landRoverData',   label: 'Land Rover' },
  renault:    { file: 'renault.js',     export: 'renaultData',     label: 'Renault' },
  rivian:     { file: 'rivian.js',      export: 'rivianData',      label: 'Rivian' },
  rollsroyce: { file: 'rolls-royce.js', export: 'rollsRoyceData',  label: 'Rolls-Royce' },
  saab:       { file: 'saab.js',        export: 'saabData',        label: 'Saab' },
  seat:       { file: 'seat.js',        export: 'seatData',        label: 'SEAT' },
  skoda:      { file: 'skoda.js',       export: 'skodaData',       label: 'Škoda' },
  smart:      { file: 'smart.js',       export: 'smartData',       label: 'Smart' },
  ssangyong:  { file: 'ssangyong.js',   export: 'ssangyongData',   label: 'SsangYong' },
  subaru:     { file: 'subatu.js',      export: 'subaruData',      label: 'Subaru' },
  suzuki:     { file: 'suzuki.js',      export: 'suzukiData',      label: 'Suzuki' },
  toyota:     { file: 'toyota.js',      export: 'toyotaData',      label: 'Toyota' },
  uaz:        { file: 'uaz.js',         export: 'uazData',         label: 'УАЗ' },
  volvo:      { file: 'volvo.js',       export: 'volvoData',       label: 'Volvo' },
  vw:         { file: 'vw.js',          export: 'vwData',          label: 'Volkswagen' },
  xpeng:      { file: 'xpeng.js',       export: 'xpengData',       label: 'Xpeng' },
};
