export const servicePresets = {
  diagECU:        [{ name: 'Диагностика ЭБУ', description: 'Полная компьютерная диагностика', price: '2 000 ₽' }],
  diagECU_plus:   [{ name: 'Диагностика ЭБУ', description: 'Расширенная диагностика с логами', price: '3 000 ₽' }],
  diagTrans:      [{ name: 'Диагностика трансмиссии', description: 'ZF/DCT/Steptronic', price: '2 500 ₽' }],
  stage1_basic:   [{ name: 'Прошивка Stage 1', description: 'Базовая оптимизация атмо ДВС', price: '10 000 ₽' }],
  stage1_na:      [{ name: 'Прошивка Stage 1', description: 'Оптимизация атмосферного ДВС', price: '12 000 ₽' }],
  stage1_turbo:   [{ name: 'Прошивка Stage 1', description: 'Тюнинг турбо двигателя', price: '15 000 ₽' }],
  stage1_turbo_hi:[{ name: 'Прошивка Stage 1', description: 'Производительный тюнинг', price: '18 000 ₽' }],
  stage1_m_perf:  [{ name: 'Прошивка Stage 1', description: 'M Performance тюнинг', price: '22 000 ₽' }],
  stage1_m:       [{ name: 'Прошивка Stage 1', description: 'M-модели Stage 1', price: '28 000 ₽' }],
  stage1_m_comp:  [{ name: 'Прошивка Stage 1', description: 'M Competition/CS тюнинг', price: '35 000 ₽' }],
  trans_zf6:      [{ name: 'Настройка ZF 6HP', description: 'Калибровка 6-ст автомата', price: '10 000 ₽' }],
  trans_zf8:      [{ name: 'Настройка ZF 8HP', description: 'Калибровка 8-ст автомата', price: '12 000 ₽' }],
  trans_dct:      [{ name: 'Настройка DCT', description: 'M DCT Launch/Shift', price: '15 000 ₽' }],
  egr_off:        [{ name: 'Отключение EGR', description: 'Программное удаление EGR', price: '7 000 ₽' }],
  dpf_off:        [{ name: 'Удаление DPF', description: 'Удаление сажевого фильтра', price: '9 000 ₽' }],
  dpf_off_adblue: [{ name: 'Удаление DPF + AdBlue', description: 'DPF + мочевина SCR', price: '11 000 ₽' }],
  gpf_off:        [{ name: 'Удаление GPF/OPF', description: 'Фильтр частиц бензиновых', price: '10 000 ₽' }],
  adblue_off:     [{ name: 'Отключение AdBlue', description: 'Удаление системы SCR', price: '8 000 ₽' }],
  vmax_off:       [{ name: 'Снятие ограничения Vmax', description: 'Разблокировка до 300 км/ч', price: '6 000 ₽' }],
  burbles:        [{ name: 'Pops & Bangs', description: 'Хлопки и выстрелы в выхлопе', price: '8 000 ₽' }],
  euro2:          [{ name: 'Прошивка на Евро 2', description: 'Отключение экологии', price: '12 000 ₽' }],
  battery_hv:     [{ name: 'Диагностика HV батареи', description: 'Проверка высоковольтной батареи', price: '5 000 ₽' }],
  hybrid_diag:    [{ name: 'Диагностика гибридной системы', description: 'eDrive инвертор/контроллер', price: '4 000 ₽' }],
  hybrid_cal:     [{ name: 'Калибровка гибридной части', description: 'Адаптации/обновления', price: '8 000 ₽' }],
  xdrive_setup:   [{ name: 'Настройка xDrive', description: 'Калибровка полного привода', price: '5 000 ₽' }],
  coding:         [{ name: 'Кодирование функций', description: 'Раскодировка опций', price: '5 000 ₽' }],
  m_mode:         [{ name: 'Активация M Mode', description: 'Раскодировка M функций', price: '7 000 ₽' }],
};

const S = (...sets) => sets.flat();

export const bmwData = {

  '3 series': {
    'E46 (1998–2005)': {
      '1.8i/2.0i (M43/N42/N46)':      S(servicePresets.stage1_basic, servicePresets.diagECU, servicePresets.coding, servicePresets.euro2),
      '2.5i (M54)':                   S(servicePresets.stage1_na, servicePresets.diagECU, servicePresets.vmax_off, servicePresets.coding),
      '3.0i (M54)':                   S(servicePresets.stage1_na, servicePresets.diagECU, servicePresets.vmax_off, servicePresets.coding),
      '2.0d/3.0d (M47/M57)':          S(servicePresets.stage1_turbo, servicePresets.dpf_off, servicePresets.egr_off, servicePresets.diagECU, servicePresets.vmax_off, servicePresets.euro2),
      'M3 3.2 (S54)':                 S(servicePresets.stage1_m, servicePresets.diagECU, servicePresets.vmax_off, servicePresets.coding),
    },
    'E90/E91/E92 pre-LCI (2005–2008)': {
      '2.0i (N46)':                   S(servicePresets.stage1_basic, servicePresets.diagECU, servicePresets.coding, servicePresets.euro2),
      '2.5i/3.0i (N52)':              S(servicePresets.stage1_na, servicePresets.diagECU, servicePresets.vmax_off, servicePresets.coding),
      '3.0si (N52)':                  S(servicePresets.stage1_na, servicePresets.trans_zf6, servicePresets.diagECU, servicePresets.vmax_off, servicePresets.coding),
      '1.8d/2.0d (N47)':              S(servicePresets.stage1_turbo, servicePresets.dpf_off, servicePresets.egr_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.euro2),
      '3.0d (M57)':                   S(servicePresets.stage1_turbo_hi, servicePresets.dpf_off, servicePresets.egr_off, servicePresets.diagECU, servicePresets.vmax_off, servicePresets.euro2),
      '335i (N54)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf6, servicePresets.diagECU, servicePresets.vmax_off, servicePresets.coding),
    },
    'E90/E91/E92 LCI (2008–2013)': {
      '2.0i (N43/N46)':               S(servicePresets.stage1_basic, servicePresets.diagECU, servicePresets.coding, servicePresets.euro2),
      '3.0i (N52N)':                  S(servicePresets.stage1_na, servicePresets.trans_zf6, servicePresets.diagECU, servicePresets.vmax_off, servicePresets.coding),
      '1.6d/2.0d (N47)':              S(servicePresets.stage1_turbo, servicePresets.dpf_off, servicePresets.egr_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.euro2),
      '3.0d (N57)':                   S(servicePresets.stage1_turbo_hi, servicePresets.dpf_off, servicePresets.egr_off, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.vmax_off, servicePresets.euro2),
      '335i (N55)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.vmax_off, servicePresets.coding),
      'M3 4.0 V8 (S65)':              S(servicePresets.stage1_m, servicePresets.trans_dct, servicePresets.diagECU, servicePresets.vmax_off, servicePresets.m_mode),
    },
    'F30/F31/F34 pre-LCI (2011–2015)': {
      '1.6i/2.0i (N13/N20)':          S(servicePresets.stage1_turbo, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.euro2),
      '3.0i (N55)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.vmax_off, servicePresets.coding),
      '1.6d/2.0d (N47)':              S(servicePresets.stage1_turbo, servicePresets.dpf_off, servicePresets.egr_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.euro2),
      '3.0d (N57)':                   S(servicePresets.stage1_turbo_hi, servicePresets.dpf_off, servicePresets.egr_off, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.vmax_off, servicePresets.euro2),
      '320i/328i xDrive (N20)':       S(servicePresets.stage1_turbo, servicePresets.xdrive_setup, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding),
      '335i (N55)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.vmax_off, servicePresets.coding),
      'M3 3.0 (S55)':                 S(servicePresets.stage1_m, servicePresets.trans_dct, servicePresets.diagECU, servicePresets.vmax_off, servicePresets.m_mode, servicePresets.burbles),
    },
    'F30/F31/F34 LCI (2015–2019)': {
      '2.0i (B48)':                   S(servicePresets.stage1_turbo, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.burbles),
      '3.0i (B58)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.vmax_off, servicePresets.coding, servicePresets.burbles),
      '2.0d (B47)':                   S(servicePresets.stage1_turbo, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.euro2),
      '3.0d (B57)':                   S(servicePresets.stage1_turbo_hi, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.vmax_off, servicePresets.euro2),
      '330e (B48 Hybrid)':            S(servicePresets.stage1_turbo, servicePresets.hybrid_diag, servicePresets.hybrid_cal, servicePresets.diagECU, servicePresets.coding),
      'M3 3.0 (S55)':                 S(servicePresets.stage1_m, servicePresets.trans_dct, servicePresets.diagECU, servicePresets.vmax_off, servicePresets.m_mode, servicePresets.burbles),
      'M3 Competition (S55)':         S(servicePresets.stage1_m_comp, servicePresets.trans_dct, servicePresets.diagECU, servicePresets.vmax_off, servicePresets.m_mode, servicePresets.burbles),
    },
    'G20/G21 pre-LCI (2018–2022)': {
      '2.0i (B48)':                   S(servicePresets.stage1_turbo, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.burbles),
      '3.0i (B58)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.vmax_off, servicePresets.coding, servicePresets.burbles),
      '2.0d (B47)':                   S(servicePresets.stage1_turbo, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.euro2),
      '3.0d (B57)':                   S(servicePresets.stage1_turbo_hi, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.vmax_off, servicePresets.euro2),
      'M340i (B58)':                  S(servicePresets.stage1_m_perf, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.vmax_off, servicePresets.m_mode, servicePresets.burbles),
      '330e (B48 Hybrid)':            S(servicePresets.stage1_turbo, servicePresets.hybrid_diag, servicePresets.hybrid_cal, servicePresets.diagECU, servicePresets.coding),
      'M3 3.0 (S58)':                 S(servicePresets.stage1_m, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.vmax_off, servicePresets.m_mode, servicePresets.burbles),
      'M3 Competition (S58)':         S(servicePresets.stage1_m_comp, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.vmax_off, servicePresets.m_mode, servicePresets.burbles),
    },
    'G20/G21 LCI (2022–н.в.)': {
      '2.0i (B48)':                   S(servicePresets.stage1_turbo, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.burbles),
      '3.0i (B58)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.vmax_off, servicePresets.coding, servicePresets.burbles),
      '2.0d (B47)':                   S(servicePresets.stage1_turbo, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.euro2),
      'M340i xDrive (B58)':           S(servicePresets.stage1_m_perf, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.xdrive_setup, servicePresets.diagECU, servicePresets.vmax_off, servicePresets.m_mode, servicePresets.burbles),
      '330e xDrive (B48 Hybrid)':     S(servicePresets.stage1_turbo, servicePresets.hybrid_diag, servicePresets.hybrid_cal, servicePresets.xdrive_setup, servicePresets.diagECU, servicePresets.coding),
      'M3 Competition xDrive (S58)':  S(servicePresets.stage1_m_comp, servicePresets.trans_zf8, servicePresets.xdrive_setup, servicePresets.diagECU, servicePresets.vmax_off, servicePresets.m_mode, servicePresets.burbles),
      'M3 CS (S58)':                  S(servicePresets.stage1_m_comp, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.vmax_off, servicePresets.m_mode, servicePresets.burbles),
    },
  },

  '5 series': {
    'E39 (1995–2003)': {
      '2.0i/2.5i (M52/M54)':          S(servicePresets.stage1_basic, servicePresets.diagECU, servicePresets.coding),
      '2.8i/3.0i (M52/M54)':          S(servicePresets.stage1_na, servicePresets.diagECU, servicePresets.coding, servicePresets.vmax_off),
      '4.4i V8 (M62)':                S(servicePresets.stage1_na, servicePresets.diagECU, servicePresets.coding, servicePresets.vmax_off),
      '2.5d/3.0d (M57)':              S(servicePresets.stage1_turbo, servicePresets.dpf_off, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2, servicePresets.vmax_off),
      'M5 5.0 V8 (S62)':              S(servicePresets.stage1_m, servicePresets.diagECU, servicePresets.m_mode, servicePresets.vmax_off),
    },
    'E60/E61 pre-LCI (2003–2007)': {
      '2.5i/3.0i (N52)':              S(servicePresets.stage1_na, servicePresets.diagECU, servicePresets.coding, servicePresets.vmax_off),
      '4.8i V8 (N62)':                S(servicePresets.stage1_na, servicePresets.trans_zf6, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off),
      '2.0d/3.0d (M47/M57)':          S(servicePresets.stage1_turbo_hi, servicePresets.dpf_off, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2, servicePresets.vmax_off),
      '535i (N54)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf6, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      'M5 5.0 V10 (S85)':             S(servicePresets.stage1_m, servicePresets.diagECU, servicePresets.m_mode, servicePresets.vmax_off),
    },
    'E60/E61 LCI (2007–2010)': {
      '3.0i (N52N/N53)':              S(servicePresets.stage1_na, servicePresets.trans_zf6, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off),
      '4.8i V8 (N62N)':               S(servicePresets.stage1_na, servicePresets.trans_zf6, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off),
      '2.0d/3.0d (N47/N57)':          S(servicePresets.stage1_turbo_hi, servicePresets.dpf_off, servicePresets.egr_off, servicePresets.trans_zf6, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.euro2, servicePresets.vmax_off),
      '535i (N54/N55)':               S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf6, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      'M5 5.0 V10 (S85)':             S(servicePresets.stage1_m, servicePresets.diagECU, servicePresets.m_mode, servicePresets.vmax_off),
    },
    'F10/F11 pre-LCI (2009–2013)': {
      '2.0i (N20)':                   S(servicePresets.stage1_turbo, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.burbles),
      '3.0i (N55)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '4.4i V8 (N63)':                S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '2.0d (N47)':                   S(servicePresets.stage1_turbo, servicePresets.dpf_off, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2),
      '3.0d (N57)':                   S(servicePresets.stage1_turbo_hi, servicePresets.dpf_off, servicePresets.egr_off, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.euro2, servicePresets.vmax_off),
      '535i (N55)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      'M5 4.4 V8 (S63)':              S(servicePresets.stage1_m, servicePresets.trans_dct, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.m_mode, servicePresets.vmax_off, servicePresets.burbles),
    },
    'F10/F11 LCI (2013–2017)': {
      '2.0i (N20)':                   S(servicePresets.stage1_turbo, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.burbles),
      '3.0i (N55)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '4.4i V8 (N63N)':               S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '2.0d (B47)':                   S(servicePresets.stage1_turbo, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2),
      '3.0d (N57N)':                  S(servicePresets.stage1_turbo_hi, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.euro2, servicePresets.vmax_off),
      '535i (N55)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      'M5 4.4 V8 (S63)':              S(servicePresets.stage1_m, servicePresets.trans_dct, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.m_mode, servicePresets.vmax_off, servicePresets.burbles),
      'M5 Competition (S63)':         S(servicePresets.stage1_m_comp, servicePresets.trans_dct, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.m_mode, servicePresets.vmax_off, servicePresets.burbles),
    },
    'G30/G31 pre-LCI (2016–2020)': {
      '2.0i (B48)':                   S(servicePresets.stage1_turbo, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.burbles),
      '3.0i (B58)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '4.4i V8 (N63)':                S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '2.0d (B47)':                   S(servicePresets.stage1_turbo, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2),
      '3.0d (B57)':                   S(servicePresets.stage1_turbo_hi, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.euro2, servicePresets.vmax_off),
      'M550i xDrive (N63)':           S(servicePresets.stage1_m_perf, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.xdrive_setup, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '530e (B48 Hybrid)':            S(servicePresets.stage1_turbo, servicePresets.hybrid_diag, servicePresets.hybrid_cal, servicePresets.diagECU, servicePresets.coding),
      'M5 4.4 V8 (S63)':              S(servicePresets.stage1_m, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.m_mode, servicePresets.vmax_off, servicePresets.burbles),
      'M5 Competition (S63)':         S(servicePresets.stage1_m_comp, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.m_mode, servicePresets.vmax_off, servicePresets.burbles),
    },
    'G30/G31 LCI (2020–н.в.)': {
      '2.0i (B48)':                   S(servicePresets.stage1_turbo, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.burbles),
      '3.0i (B58)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '2.0d (B47)':                   S(servicePresets.stage1_turbo, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2),
      '3.0d (B57)':                   S(servicePresets.stage1_turbo_hi, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.euro2, servicePresets.vmax_off),
      'M550i xDrive (N63)':           S(servicePresets.stage1_m_perf, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.xdrive_setup, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '530e xDrive (B48 Hybrid)':     S(servicePresets.stage1_turbo, servicePresets.hybrid_diag, servicePresets.hybrid_cal, servicePresets.xdrive_setup, servicePresets.diagECU, servicePresets.coding),
      'M5 Competition xDrive (S63)':  S(servicePresets.stage1_m_comp, servicePresets.trans_zf8, servicePresets.xdrive_setup, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.m_mode, servicePresets.vmax_off, servicePresets.burbles),
      'M5 CS (S63)':                  S(servicePresets.stage1_m_comp, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.m_mode, servicePresets.vmax_off, servicePresets.burbles),
    },
  },

  '7 series': {
    'E38 (1994–2001)': {
      '2.8i/3.5i (M52/M62)':          S(servicePresets.stage1_na, servicePresets.diagECU, servicePresets.coding, servicePresets.vmax_off),
      '4.4i V8 (M62)':                S(servicePresets.stage1_na, servicePresets.diagECU, servicePresets.coding, servicePresets.vmax_off),
      '5.4 V12 (M73)':                S(servicePresets.stage1_na, servicePresets.diagECU, servicePresets.coding, servicePresets.vmax_off),
    },
    'E65/E66 (2001–2008)': {
      '3.0i (N52)':                   S(servicePresets.stage1_na, servicePresets.diagECU, servicePresets.coding, servicePresets.vmax_off),
      '4.4i V8 (N62)':                S(servicePresets.stage1_na, servicePresets.trans_zf6, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off),
      '6.0 V12 (N73)':                S(servicePresets.stage1_na, servicePresets.trans_zf6, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off),
      '3.0d (M57)':                   S(servicePresets.stage1_turbo_hi, servicePresets.dpf_off, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2, servicePresets.vmax_off),
    },
    'F01/F02 pre-LCI (2008–2012)': {
      '3.0i (N52/N55)':               S(servicePresets.stage1_turbo, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.burbles),
      '4.4i V8 (N63)':                S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '6.0 V12 (N74)':                S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '3.0d (N57)':                   S(servicePresets.stage1_turbo_hi, servicePresets.dpf_off, servicePresets.egr_off, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.euro2, servicePresets.vmax_off),
      '740i (N55)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
    },
    'F01/F02 LCI (2012–2015)': {
      '3.0i (N55)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '4.4i V8 (N63)':                S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '6.0 V12 (N74)':                S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '3.0d (N57)':                   S(servicePresets.stage1_turbo_hi, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.euro2, servicePresets.vmax_off),
      '750i xDrive (N63)':            S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.xdrive_setup, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
    },
    'G11/G12 pre-LCI (2015–2019)': {
      '2.0i (B48)':                   S(servicePresets.stage1_turbo, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.burbles),
      '3.0i (B58)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '4.4i V8 (N63)':                S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '6.6 V12 (N74)':                S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '3.0d (B57)':                   S(servicePresets.stage1_turbo_hi, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.euro2, servicePresets.vmax_off),
      'M760Li xDrive (N74)':          S(servicePresets.stage1_m_perf, servicePresets.trans_zf8, servicePresets.xdrive_setup, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
    },
    'G11/G12 LCI (2019–2022)': {
      '3.0i (B58)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '4.4i V8 (N63)':                S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '3.0d (B57)':                   S(servicePresets.stage1_turbo_hi, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.euro2, servicePresets.vmax_off),
      '745e xDrive (B58 Hybrid)':     S(servicePresets.stage1_turbo_hi, servicePresets.hybrid_diag, servicePresets.hybrid_cal, servicePresets.xdrive_setup, servicePresets.diagECU, servicePresets.coding),
      'M760Li xDrive (N74)':          S(servicePresets.stage1_m_perf, servicePresets.trans_zf8, servicePresets.xdrive_setup, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
    },
    'G70 (2022–н.в.)': {
      '3.0i (B58)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '4.4i V8 (S68)':                S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '3.0d (B57)':                   S(servicePresets.stage1_turbo_hi, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2, servicePresets.vmax_off),
      '760i xDrive (B58 Hybrid)':     S(servicePresets.stage1_turbo_hi, servicePresets.hybrid_diag, servicePresets.hybrid_cal, servicePresets.xdrive_setup, servicePresets.diagECU, servicePresets.coding),
      'i7 xDrive60':                  S(servicePresets.battery_hv, servicePresets.diagECU_plus),
    },
  },

  'x1': {
    'E84 pre-LCI (2009–2012)': {
      '2.0i (N46)':                   S(servicePresets.stage1_turbo, servicePresets.diagECU, servicePresets.coding),
      '3.0i (N52)':                   S(servicePresets.stage1_na, servicePresets.diagECU, servicePresets.coding, servicePresets.vmax_off),
      '2.0d (N47)':                   S(servicePresets.stage1_turbo, servicePresets.dpf_off, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2),
    },
    'E84 LCI (2012–2015)': {
      '2.0i (N20)':                   S(servicePresets.stage1_turbo, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.burbles),
      '2.0d (N47)':                   S(servicePresets.stage1_turbo, servicePresets.dpf_off, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2),
    },
    'F48 pre-LCI (2015–2019)': {
      '1.5i/2.0i (B38/B48)':          S(servicePresets.stage1_turbo, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.burbles),
      '2.0d (B47)':                   S(servicePresets.stage1_turbo, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2),
      'xDrive25i (B48)':              S(servicePresets.stage1_turbo, servicePresets.xdrive_setup, servicePresets.diagECU, servicePresets.coding, servicePresets.burbles),
    },
    'F48 LCI (2019–2022)': {
      '1.5i/2.0i (B38/B48)':          S(servicePresets.stage1_turbo, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.burbles),
      '2.0d (B47)':                   S(servicePresets.stage1_turbo, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2),
      'xDrive25e (B38 Hybrid)':       S(servicePresets.stage1_turbo, servicePresets.hybrid_diag, servicePresets.hybrid_cal, servicePresets.xdrive_setup, servicePresets.diagECU, servicePresets.coding),
    },
    'U11 (2022–н.в.)': {
      '2.0i (B48)':                   S(servicePresets.stage1_turbo, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.burbles),
      '2.0d (B47)':                   S(servicePresets.stage1_turbo, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2),
      'xDrive30e (B48 Hybrid)':       S(servicePresets.stage1_turbo, servicePresets.hybrid_diag, servicePresets.hybrid_cal, servicePresets.xdrive_setup, servicePresets.diagECU, servicePresets.coding),
      'iX1 xDrive30':                 S(servicePresets.battery_hv, servicePresets.diagECU_plus),
    },
  },

  'x3': {
    'E83 (2003–2010)': {
      '2.0i/2.5i (N46/N52)':          S(servicePresets.stage1_basic, servicePresets.diagECU, servicePresets.coding),
      '3.0i (N52)':                   S(servicePresets.stage1_na, servicePresets.diagECU, servicePresets.coding, servicePresets.vmax_off),
      '2.0d/3.0d (M47/N47)':          S(servicePresets.stage1_turbo, servicePresets.dpf_off, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2, servicePresets.vmax_off),
    },
    'F25 pre-LCI (2010–2014)': {
      '2.0i (N20)':                   S(servicePresets.stage1_turbo, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.burbles),
      '3.0i (N55)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '2.0d (N47)':                   S(servicePresets.stage1_turbo, servicePresets.dpf_off, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2),
      '3.0d (N57)':                   S(servicePresets.stage1_turbo_hi, servicePresets.dpf_off, servicePresets.egr_off, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.euro2, servicePresets.vmax_off),
    },
    'F25 LCI (2014–2017)': {
      '2.0i (B48)':                   S(servicePresets.stage1_turbo, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.burbles),
      '3.0i (N55)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '2.0d (B47)':                   S(servicePresets.stage1_turbo, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2),
      '3.0d (N57)':                   S(servicePresets.stage1_turbo_hi, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.euro2, servicePresets.vmax_off),
    },
    'G01 pre-LCI (2017–2021)': {
      '2.0i (B48)':                   S(servicePresets.stage1_turbo, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.burbles),
      '3.0i (B58)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '2.0d (B47)':                   S(servicePresets.stage1_turbo, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2),
      '3.0d (B57)':                   S(servicePresets.stage1_turbo_hi, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.euro2, servicePresets.vmax_off),
      'M40i (B58)':                   S(servicePresets.stage1_m_perf, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      'X3 M Competition (S58)':       S(servicePresets.stage1_m_comp, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.m_mode, servicePresets.vmax_off, servicePresets.burbles),
    },
    'G01 LCI (2021–н.в.)': {
      '2.0i (B48)':                   S(servicePresets.stage1_turbo, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.burbles),
      '3.0i (B58)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '2.0d (B47)':                   S(servicePresets.stage1_turbo, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2),
      '3.0d (B57)':                   S(servicePresets.stage1_turbo_hi, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2, servicePresets.vmax_off),
      'M40i xDrive (B58)':            S(servicePresets.stage1_m_perf, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.xdrive_setup, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '30e xDrive (B48 Hybrid)':      S(servicePresets.stage1_turbo, servicePresets.hybrid_diag, servicePresets.hybrid_cal, servicePresets.xdrive_setup, servicePresets.diagECU, servicePresets.coding),
      'X3 M Competition (S58)':       S(servicePresets.stage1_m_comp, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.m_mode, servicePresets.vmax_off, servicePresets.burbles),
    },
  },

  'x5': {
    'E53 (1999–2006)': {
      '3.0i (M54)':                   S(servicePresets.stage1_na, servicePresets.diagECU, servicePresets.coding, servicePresets.vmax_off),
      '4.4i V8 (M62)':                S(servicePresets.stage1_na, servicePresets.diagECU, servicePresets.coding, servicePresets.vmax_off),
      '4.6is/4.8is (M62)':            S(servicePresets.stage1_na, servicePresets.diagECU, servicePresets.coding, servicePresets.vmax_off),
      '3.0d (M57)':                   S(servicePresets.stage1_turbo, servicePresets.dpf_off, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2, servicePresets.vmax_off),
    },
    'E70 pre-LCI (2006–2010)': {
      '3.0i (N52)':                   S(servicePresets.stage1_na, servicePresets.diagECU, servicePresets.coding, servicePresets.vmax_off),
      '4.8i V8 (N62)':                S(servicePresets.stage1_na, servicePresets.trans_zf6, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off),
      '3.0d (M57)':                   S(servicePresets.stage1_turbo_hi, servicePresets.dpf_off, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2, servicePresets.vmax_off),
      'xDrive35i (N54)':              S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf6, servicePresets.xdrive_setup, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
    },
    'E70 LCI (2010–2013)': {
      '3.0i (N55)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '4.4i V8 (N63)':                S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '3.0d (N57)':                   S(servicePresets.stage1_turbo_hi, servicePresets.dpf_off, servicePresets.egr_off, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.euro2, servicePresets.vmax_off),
      'xDrive50i (N63)':              S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.xdrive_setup, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      'M 4.4 V8 (S63)':               S(servicePresets.stage1_m, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.m_mode, servicePresets.vmax_off, servicePresets.burbles),
    },
    'F15 pre-LCI (2013–2017)': {
      '2.0i (N20)':                   S(servicePresets.stage1_turbo, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.burbles),
      '3.0i (N55)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '4.4i V8 (N63)':                S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '2.0d (N47)':                   S(servicePresets.stage1_turbo, servicePresets.dpf_off, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2),
      '3.0d (N57)':                   S(servicePresets.stage1_turbo_hi, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.euro2, servicePresets.vmax_off),
      'xDrive40e (N20 Hybrid)':       S(servicePresets.stage1_turbo, servicePresets.hybrid_diag, servicePresets.hybrid_cal, servicePresets.xdrive_setup, servicePresets.diagECU, servicePresets.coding),
      'M 4.4 V8 (S63)':               S(servicePresets.stage1_m, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.m_mode, servicePresets.vmax_off, servicePresets.burbles),
    },
    'F15 LCI (2017–2018)': {
      '2.0i (B48)':                   S(servicePresets.stage1_turbo, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.burbles),
      '3.0i (B58)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '4.4i V8 (N63)':                S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '3.0d (B57)':                   S(servicePresets.stage1_turbo_hi, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2, servicePresets.vmax_off),
      'xDrive40e (B48 Hybrid)':       S(servicePresets.stage1_turbo, servicePresets.hybrid_diag, servicePresets.hybrid_cal, servicePresets.xdrive_setup, servicePresets.diagECU, servicePresets.coding),
      'M 4.4 V8 (S63)':               S(servicePresets.stage1_m_comp, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.m_mode, servicePresets.vmax_off, servicePresets.burbles),
    },
    'G05 pre-LCI (2018–2022)': {
      '2.0i (B48)':                   S(servicePresets.stage1_turbo, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.burbles),
      '3.0i (B58)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '4.4i V8 (N63)':                S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '3.0d (B57)':                   S(servicePresets.stage1_turbo_hi, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2, servicePresets.vmax_off),
      'M50i (N63)':                   S(servicePresets.stage1_m_perf, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      'xDrive45e (B58 Hybrid)':       S(servicePresets.stage1_turbo_hi, servicePresets.hybrid_diag, servicePresets.hybrid_cal, servicePresets.xdrive_setup, servicePresets.diagECU, servicePresets.coding),
      'X5 M Competition (S63)':       S(servicePresets.stage1_m_comp, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.m_mode, servicePresets.vmax_off, servicePresets.burbles),
    },
    'G05 LCI (2022–н.в.)': {
      '3.0i (B58)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '4.4i V8 (S68)':                S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '3.0d (B57)':                   S(servicePresets.stage1_turbo_hi, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2, servicePresets.vmax_off),
      'M60i xDrive (S68)':            S(servicePresets.stage1_m_perf, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.xdrive_setup, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      'xDrive50e (B58 Hybrid)':       S(servicePresets.stage1_turbo_hi, servicePresets.hybrid_diag, servicePresets.hybrid_cal, servicePresets.xdrive_setup, servicePresets.diagECU, servicePresets.coding),
      'X5 M Competition (S63)':       S(servicePresets.stage1_m_comp, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.m_mode, servicePresets.vmax_off, servicePresets.burbles),
      'iX5 Hydrogen':                 S(servicePresets.battery_hv, servicePresets.diagECU_plus),
    },
  },

  'x6': {
    'E71 (2008–2014)': {
      '3.0i (N55)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '4.4i V8 (N63)':                S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '3.0d (N57)':                   S(servicePresets.stage1_turbo_hi, servicePresets.dpf_off, servicePresets.egr_off, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.euro2, servicePresets.vmax_off),
      'M 4.4 V8 (S63)':               S(servicePresets.stage1_m, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.m_mode, servicePresets.vmax_off, servicePresets.burbles),
    },
    'F16 pre-LCI (2014–2017)': {
      '3.0i (N55)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '4.4i V8 (N63)':                S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '3.0d (N57)':                   S(servicePresets.stage1_turbo_hi, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.euro2, servicePresets.vmax_off),
      'M 4.4 V8 (S63)':               S(servicePresets.stage1_m, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.m_mode, servicePresets.vmax_off, servicePresets.burbles),
    },
    'F16 LCI (2017–2019)': {
      '3.0i (B58)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '4.4i V8 (N63)':                S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '3.0d (B57)':                   S(servicePresets.stage1_turbo_hi, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2, servicePresets.vmax_off),
      'M 4.4 V8 (S63)':               S(servicePresets.stage1_m_comp, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.m_mode, servicePresets.vmax_off, servicePresets.burbles),
    },
    'G06 pre-LCI (2019–2023)': {
      '3.0i (B58)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '4.4i V8 (N63)':                S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '3.0d (B57)':                   S(servicePresets.stage1_turbo_hi, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2, servicePresets.vmax_off),
      'M50i (N63)':                   S(servicePresets.stage1_m_perf, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      'X6 M Competition (S63)':       S(servicePresets.stage1_m_comp, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.m_mode, servicePresets.vmax_off, servicePresets.burbles),
    },
    'G06 LCI (2023–н.в.)': {
      '3.0i (B58)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '4.4i V8 (S68)':                S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      'M60i xDrive (S68)':            S(servicePresets.stage1_m_perf, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.xdrive_setup, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      'X6 M Competition (S63)':       S(servicePresets.stage1_m_comp, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.m_mode, servicePresets.vmax_off, servicePresets.burbles),
    },
  },

  'x7': {
    'G07 pre-LCI (2018–2022)': {
      '3.0i (B58)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '4.4i V8 (N63)':                S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '3.0d (B57)':                   S(servicePresets.stage1_turbo_hi, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2, servicePresets.vmax_off),
      'M50i (N63)':                   S(servicePresets.stage1_m_perf, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
    },
    'G07 LCI (2022–н.в.)': {
      '3.0i (B58)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '4.4i V8 (S68)':                S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '3.0d (B57)':                   S(servicePresets.stage1_turbo_hi, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2, servicePresets.vmax_off),
      'M60i xDrive (S68)':            S(servicePresets.stage1_m_perf, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.xdrive_setup, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      'xDrive60i (B58 Hybrid)':       S(servicePresets.stage1_turbo_hi, servicePresets.hybrid_diag, servicePresets.hybrid_cal, servicePresets.xdrive_setup, servicePresets.diagECU, servicePresets.coding),
    },
  },

  'x4': {
    'F26 (2014–2018)': {
      '2.0i (N20)':                   S(servicePresets.stage1_turbo, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.burbles),
      '3.0i (N55)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '2.0d (N47/B47)':               S(servicePresets.stage1_turbo, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2),
      '3.0d (N57)':                   S(servicePresets.stage1_turbo_hi, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2, servicePresets.vmax_off),
      'M40i (N55)':                   S(servicePresets.stage1_m_perf, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
    },
    'G02 pre-LCI (2018–2021)': {
      '2.0i (B48)':                   S(servicePresets.stage1_turbo, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.burbles),
      '3.0i (B58)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '2.0d (B47)':                   S(servicePresets.stage1_turbo, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2),
      '3.0d (B57)':                   S(servicePresets.stage1_turbo_hi, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2, servicePresets.vmax_off),
      'M40i (B58)':                   S(servicePresets.stage1_m_perf, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      'X4 M Competition (S58)':       S(servicePresets.stage1_m_comp, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.m_mode, servicePresets.vmax_off, servicePresets.burbles),
    },
    'G02 LCI (2021–н.в.)': {
      '2.0i (B48)':                   S(servicePresets.stage1_turbo, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.burbles),
      '3.0i (B58)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '2.0d (B47)':                   S(servicePresets.stage1_turbo, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2),
      'M40i xDrive (B58)':            S(servicePresets.stage1_m_perf, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.xdrive_setup, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      'X4 M Competition (S58)':       S(servicePresets.stage1_m_comp, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.m_mode, servicePresets.vmax_off, servicePresets.burbles),
    },
  },

  '4 series': {
    'F32/F33/F36 pre-LCI (2013–2017)': {
      '2.0i (N20/B48)':               S(servicePresets.stage1_turbo, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.burbles),
      '3.0i (N55)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '2.0d (N47/B47)':               S(servicePresets.stage1_turbo, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2),
      '3.0d (N57)':                   S(servicePresets.stage1_turbo_hi, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2, servicePresets.vmax_off),
      '435i (N55)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      'M4 3.0 (S55)':                 S(servicePresets.stage1_m, servicePresets.trans_dct, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.m_mode, servicePresets.vmax_off, servicePresets.burbles),
    },
    'F32/F33/F36 LCI (2017–2020)': {
      '2.0i (B48)':                   S(servicePresets.stage1_turbo, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.burbles),
      '3.0i (B58)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '2.0d (B47)':                   S(servicePresets.stage1_turbo, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2),
      '3.0d (B57)':                   S(servicePresets.stage1_turbo_hi, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2, servicePresets.vmax_off),
      '440i (B58)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      'M4 3.0 (S55)':                 S(servicePresets.stage1_m, servicePresets.trans_dct, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.m_mode, servicePresets.vmax_off, servicePresets.burbles),
      'M4 Competition (S55)':         S(servicePresets.stage1_m_comp, servicePresets.trans_dct, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.m_mode, servicePresets.vmax_off, servicePresets.burbles),
    },
    'G22/G23/G26 pre-LCI (2020–2023)': {
      '2.0i (B48)':                   S(servicePresets.stage1_turbo, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.burbles),
      '3.0i (B58)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      '2.0d (B47)':                   S(servicePresets.stage1_turbo, servicePresets.dpf_off_adblue, servicePresets.egr_off, servicePresets.diagECU, servicePresets.euro2),
      'M440i xDrive (B58)':           S(servicePresets.stage1_m_perf, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.xdrive_setup, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      'M4 3.0 (S58)':                 S(servicePresets.stage1_m, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.m_mode, servicePresets.vmax_off, servicePresets.burbles),
      'M4 Competition (S58)':         S(servicePresets.stage1_m_comp, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.m_mode, servicePresets.vmax_off, servicePresets.burbles),
    },
    'G22/G23/G26 LCI (2023–н.в.)': {
      '2.0i (B48)':                   S(servicePresets.stage1_turbo, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.burbles),
      '3.0i (B58)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      'M440i xDrive (B58)':           S(servicePresets.stage1_m_perf, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.xdrive_setup, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      'M4 Competition xDrive (S58)':  S(servicePresets.stage1_m_comp, servicePresets.trans_zf8, servicePresets.xdrive_setup, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.m_mode, servicePresets.vmax_off, servicePresets.burbles),
      'M4 CS (S58)':                  S(servicePresets.stage1_m_comp, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.m_mode, servicePresets.vmax_off, servicePresets.burbles),
    },
  },

  'i3': {
    'I01 (2013–2022)': {
      'i3 (60Ah/94Ah/120Ah)':         S(servicePresets.battery_hv, servicePresets.diagECU_plus),
      'i3s (120Ah)':                  S(servicePresets.battery_hv, servicePresets.diagECU_plus),
      'i3 REx (Range Extender)':      S(servicePresets.battery_hv, servicePresets.hybrid_diag),
    },
  },

  'i4': {
    'G26 (2021–н.в.)': {
      'i4 eDrive35/eDrive40':         S(servicePresets.battery_hv, servicePresets.diagECU_plus),
      'i4 M50 xDrive':                S(servicePresets.battery_hv, servicePresets.diagECU_plus, servicePresets.m_mode),
    },
  },

  'ix': {
    'I20 (2021–н.в.)': {
      'iX xDrive40':                  S(servicePresets.battery_hv, servicePresets.diagECU_plus),
      'iX xDrive50':                  S(servicePresets.battery_hv, servicePresets.diagECU_plus),
      'iX M60':                       S(servicePresets.battery_hv, servicePresets.diagECU_plus, servicePresets.m_mode),
    },
  },

  'i8': {
    'I12 (2014–2020)': {
      'i8 1.5 Hybrid (B38)':          S(servicePresets.stage1_turbo, servicePresets.hybrid_diag, servicePresets.hybrid_cal, servicePresets.battery_hv),
      'i8 Roadster':                  S(servicePresets.stage1_turbo, servicePresets.hybrid_diag, servicePresets.hybrid_cal, servicePresets.battery_hv),
    },
  },

  'z4': {
    'E85/E86 (2002–2008)': {
      '2.0i/2.5i (M54)':              S(servicePresets.stage1_basic, servicePresets.diagECU, servicePresets.coding),
      '3.0i (M54/N52)':               S(servicePresets.stage1_na, servicePresets.diagECU, servicePresets.coding, servicePresets.vmax_off),
      'M Roadster/Coupe 3.2 (S54)':   S(servicePresets.stage1_m, servicePresets.diagECU, servicePresets.m_mode, servicePresets.vmax_off),
    },
    'E89 (2009–2016)': {
      '2.0i (N20)':                   S(servicePresets.stage1_turbo, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.burbles),
      '3.0i (N52)':                   S(servicePresets.stage1_na, servicePresets.trans_zf8, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off),
      'sDrive35i (N54/N55)':          S(servicePresets.stage1_turbo_hi, servicePresets.trans_dct, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      'sDrive35is (N54)':             S(servicePresets.stage1_turbo_hi, servicePresets.trans_dct, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
    },
    'G29 (2018–н.в.)': {
      '2.0i (B48)':                   S(servicePresets.stage1_turbo, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.burbles),
      '3.0i (B58)':                   S(servicePresets.stage1_turbo_hi, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
      'M40i (B58)':                   S(servicePresets.stage1_m_perf, servicePresets.trans_zf8, servicePresets.gpf_off, servicePresets.diagECU, servicePresets.diagTrans, servicePresets.coding, servicePresets.vmax_off, servicePresets.burbles),
    },
  },

  'm3':               { 'см. 3 Series соответствующего поколения': S() },
  'm5':               { 'см. 5 Series соответствующего поколения': S() },
  'x3 m':             { 'см. X3 соответствующего поколения': S() },
  'x4 m':             { 'см. X4 соответствующего поколения': S() },
  'x5 m':             { 'см. X5 соответствующего поколения': S() },
  'x6 m':             { 'см. X6 соответствующего поколения': S() },
  'm4':               { 'см. 4 Series соответствующего поколения': S() },
  'm2':               { 'Доступна диагностика, уточняйте комплектацию': S() },
  'm8':               { 'Доступна диагностика, уточняйте комплектацию': S() },
};