export const servicePresets = {
  diagECU:        [{ name: 'Диагностика ЭБУ', description: 'Полная компьютерная диагностика', price: '3 000 ₽' }],
  diagECU_plus:   [{ name: 'Диагностика ЭБУ', description: 'Расширенная диагностика с логами', price: '5 000 ₽' }],
  battery_diag:   [{ name: 'Диагностика HV батареи', description: 'Проверка высоковольтной батареи', price: '7 000 ₽' }],
  battery_deep:   [{ name: 'Углубленная диагностика батареи', description: 'Полный анализ ячеек и BMS', price: '11 000 ₽' }],
  battery_cal:    [{ name: 'Калибровка батареи', description: 'Адаптация и балансировка BMS', price: '9 000 ₽' }],
  battery_swap:   [{ name: 'Диагностика Battery Swap', description: 'Проверка системы замены батареи', price: '6 000 ₽' }],
  inverter_diag:  [{ name: 'Диагностика инвертора', description: 'Проверка силовой электроники', price: '6 000 ₽' }],
  motor_diag:     [{ name: 'Диагностика электромотора', description: 'Проверка тягового двигателя', price: '5 000 ₽' }],
  motor_dual:     [{ name: 'Диагностика Dual Motor', description: '2 электромотора AWD', price: '7 000 ₽' }],
  cooling_diag:   [{ name: 'Диагностика системы охлаждения', description: 'Терморегуляция батареи и моторов', price: '5 000 ₽' }],
  charging_diag:  [{ name: 'Диагностика зарядной системы', description: 'DC/AC charging система', price: '6 000 ₽' }],
  software_update:[{ name: 'Обновление ПО', description: 'NIO OS/Firmware updates', price: '7 000 ₽' }],
  niopilot_diag:  [{ name: 'Диагностика NIO Pilot', description: 'ADAS и автопилот', price: '7 000 ₽' }],
  niopilot_cal:   [{ name: 'Калибровка NIO Pilot', description: 'Настройка камер и радаров', price: '11 000 ₽' }],
  niopilot_plus:  [{ name: 'Диагностика NIO Pilot+', description: 'Расширенный автопилот NAD', price: '9 000 ₽' }],
  airsusp_diag:   [{ name: 'Диагностика пневмоподвески', description: 'Air suspension system', price: '6 000 ₽' }],
  airsusp_cal:    [{ name: 'Калибровка подвески', description: 'Адаптация высоты и жесткости', price: '8 000 ₽' }],
  vmax_off:       [{ name: 'Снятие ограничения Vmax', description: 'Разблокировка максимальной скорости', price: '9 000 ₽' }],
  power_tune:     [{ name: 'Настройка отдачи', description: 'Оптимизация power delivery', price: '12 000 ₽' }],
  power_tune_hi:  [{ name: 'Производительная настройка', description: 'Увеличение мощности Performance', price: '18 000 ₽' }],
  regen_tune:     [{ name: 'Настройка рекуперации', description: 'Калибровка режимов торможения', price: '5 000 ₽' }],
  torque_vector:  [{ name: 'Настройка Torque Vectoring', description: 'Распределение крутящего момента', price: '9 000 ₽' }],
  launch_control: [{ name: 'Активация Launch Control', description: 'Режим максимального разгона', price: '7 000 ₽' }],
  coding:         [{ name: 'Кодирование функций', description: 'Раскодировка опций', price: '6 000 ₽' }],
  coding_premium: [{ name: 'Расширенное кодирование', description: 'Активация премиум функций', price: '12 000 ₽' }],
  nomi_coding:    [{ name: 'Настройка NOMI', description: 'Персонализация AI ассистента', price: '4 000 ₽' }],
  dtc_off:        [{ name: 'Отключение DTC', description: 'Удаление кодов ошибок', price: '4 000 ₽' }],
};

const S = (...sets) => sets.flat();

export const nioData = {

  'es8': {
    '1 поколение дорест (2018–2020)': {
      'ES8 6-seat (480 л.с., 70 кВтч)':        S(servicePresets.battery_diag, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_diag, servicePresets.airsusp_diag, servicePresets.battery_swap, servicePresets.coding, servicePresets.regen_tune, servicePresets.nomi_coding),
      'ES8 7-seat (480 л.с., 70 кВтч)':        S(servicePresets.battery_diag, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_diag, servicePresets.airsusp_diag, servicePresets.battery_swap, servicePresets.coding, servicePresets.regen_tune, servicePresets.nomi_coding),
      'ES8 (480 л.с., 84 кВтч)':               S(servicePresets.battery_diag, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_diag, servicePresets.airsusp_diag, servicePresets.battery_swap, servicePresets.coding, servicePresets.regen_tune, servicePresets.nomi_coding, servicePresets.vmax_off),
    },
    '1 поколение FL (2020–2022)': {
      'ES8 (544 л.с., 70 кВтч)':               S(servicePresets.battery_diag, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_diag, servicePresets.niopilot_cal, servicePresets.airsusp_diag, servicePresets.airsusp_cal, servicePresets.battery_swap, servicePresets.power_tune, servicePresets.coding, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.nomi_coding),
      'ES8 (544 л.с., 100 кВтч)':              S(servicePresets.battery_deep, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_diag, servicePresets.niopilot_cal, servicePresets.airsusp_diag, servicePresets.airsusp_cal, servicePresets.battery_swap, servicePresets.power_tune, servicePresets.coding, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.nomi_coding, servicePresets.vmax_off),
    },
    '2 поколение (2022–2025)': {
      'ES8 (653 л.с., 75 кВтч)':               S(servicePresets.battery_diag, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU_plus, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_plus, servicePresets.niopilot_cal, servicePresets.airsusp_diag, servicePresets.airsusp_cal, servicePresets.battery_swap, servicePresets.power_tune_hi, servicePresets.coding_premium, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.launch_control, servicePresets.nomi_coding, servicePresets.vmax_off),
      'ES8 (653 л.с., 100 кВтч)':              S(servicePresets.battery_deep, servicePresets.battery_cal, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU_plus, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_plus, servicePresets.niopilot_cal, servicePresets.airsusp_diag, servicePresets.airsusp_cal, servicePresets.battery_swap, servicePresets.power_tune_hi, servicePresets.coding_premium, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.launch_control, servicePresets.nomi_coding, servicePresets.vmax_off),
      'ES8 (653 л.с., 150 кВтч)':              S(servicePresets.battery_deep, servicePresets.battery_cal, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU_plus, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_plus, servicePresets.niopilot_cal, servicePresets.airsusp_diag, servicePresets.airsusp_cal, servicePresets.battery_swap, servicePresets.power_tune_hi, servicePresets.coding_premium, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.launch_control, servicePresets.nomi_coding, servicePresets.vmax_off),
    },
    '3 поколение (2025–н.в.)': {
      'ES8 (707 л.с., 90 кВтч)':               S(servicePresets.battery_deep, servicePresets.battery_cal, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU_plus, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_plus, servicePresets.niopilot_cal, servicePresets.airsusp_diag, servicePresets.airsusp_cal, servicePresets.battery_swap, servicePresets.power_tune_hi, servicePresets.coding_premium, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.launch_control, servicePresets.nomi_coding, servicePresets.vmax_off),
      'ES8 (707 л.с., 100 кВтч)':              S(servicePresets.battery_deep, servicePresets.battery_cal, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU_plus, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_plus, servicePresets.niopilot_cal, servicePresets.airsusp_diag, servicePresets.airsusp_cal, servicePresets.battery_swap, servicePresets.power_tune_hi, servicePresets.coding_premium, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.launch_control, servicePresets.nomi_coding, servicePresets.vmax_off),
      'ES8 (707 л.с., 150 кВтч)':              S(servicePresets.battery_deep, servicePresets.battery_cal, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU_plus, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_plus, servicePresets.niopilot_cal, servicePresets.airsusp_diag, servicePresets.airsusp_cal, servicePresets.battery_swap, servicePresets.power_tune_hi, servicePresets.coding_premium, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.launch_control, servicePresets.nomi_coding, servicePresets.vmax_off),
    },
  },

  'es6': {
    '1 поколение (2019–2023)': {
      'ES6 Performance (544 л.с., 70 кВтч)':   S(servicePresets.battery_diag, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_diag, servicePresets.niopilot_cal, servicePresets.airsusp_diag, servicePresets.battery_swap, servicePresets.power_tune, servicePresets.coding, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.nomi_coding, servicePresets.vmax_off),
      'ES6 Performance (544 л.с., 84 кВтч)':   S(servicePresets.battery_diag, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_diag, servicePresets.niopilot_cal, servicePresets.airsusp_diag, servicePresets.battery_swap, servicePresets.power_tune, servicePresets.coding, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.nomi_coding, servicePresets.vmax_off),
      'ES6 Performance (544 л.с., 100 кВтч)':  S(servicePresets.battery_deep, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_diag, servicePresets.niopilot_cal, servicePresets.airsusp_diag, servicePresets.battery_swap, servicePresets.power_tune, servicePresets.coding, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.launch_control, servicePresets.nomi_coding, servicePresets.vmax_off),
    },
    '2 поколение (2023–2025)': {
      'ES6 (490 л.с., 75 кВтч)':               S(servicePresets.battery_diag, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU_plus, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_plus, servicePresets.niopilot_cal, servicePresets.airsusp_diag, servicePresets.airsusp_cal, servicePresets.battery_swap, servicePresets.power_tune, servicePresets.coding_premium, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.nomi_coding, servicePresets.vmax_off),
      'ES6 (490 л.с., 100 кВтч)':              S(servicePresets.battery_deep, servicePresets.battery_cal, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU_plus, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_plus, servicePresets.niopilot_cal, servicePresets.airsusp_diag, servicePresets.airsusp_cal, servicePresets.battery_swap, servicePresets.power_tune, servicePresets.coding_premium, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.launch_control, servicePresets.nomi_coding, servicePresets.vmax_off),
      'ES6 (490 л.с., 150 кВтч)':              S(servicePresets.battery_deep, servicePresets.battery_cal, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU_plus, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_plus, servicePresets.niopilot_cal, servicePresets.airsusp_diag, servicePresets.airsusp_cal, servicePresets.battery_swap, servicePresets.power_tune, servicePresets.coding_premium, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.launch_control, servicePresets.nomi_coding, servicePresets.vmax_off),
    },
    '2 поколение FL (2025–н.в.)': {
      'ES6 (490 л.с., 90 кВтч)':               S(servicePresets.battery_deep, servicePresets.battery_cal, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU_plus, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_plus, servicePresets.niopilot_cal, servicePresets.airsusp_diag, servicePresets.airsusp_cal, servicePresets.battery_swap, servicePresets.power_tune, servicePresets.coding_premium, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.launch_control, servicePresets.nomi_coding, servicePresets.vmax_off),
      'ES6 (490 л.с., 100 кВтч)':              S(servicePresets.battery_deep, servicePresets.battery_cal, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU_plus, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_plus, servicePresets.niopilot_cal, servicePresets.airsusp_diag, servicePresets.airsusp_cal, servicePresets.battery_swap, servicePresets.power_tune, servicePresets.coding_premium, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.launch_control, servicePresets.nomi_coding, servicePresets.vmax_off),
      'ES6 (490 л.с., 150 кВтч)':              S(servicePresets.battery_deep, servicePresets.battery_cal, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU_plus, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_plus, servicePresets.niopilot_cal, servicePresets.airsusp_diag, servicePresets.airsusp_cal, servicePresets.battery_swap, servicePresets.power_tune, servicePresets.coding_premium, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.launch_control, servicePresets.nomi_coding, servicePresets.vmax_off),
    },
  },

  'ec6': {
    '1 поколение (2020–2023)': {
      'EC6 Performance (544 л.с., 70 кВтч)':   S(servicePresets.battery_diag, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_diag, servicePresets.niopilot_cal, servicePresets.airsusp_diag, servicePresets.battery_swap, servicePresets.power_tune, servicePresets.coding, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.nomi_coding, servicePresets.vmax_off),
      'EC6 Performance (544 л.с., 84 кВтч)':   S(servicePresets.battery_diag, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_diag, servicePresets.niopilot_cal, servicePresets.airsusp_diag, servicePresets.battery_swap, servicePresets.power_tune, servicePresets.coding, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.nomi_coding, servicePresets.vmax_off),
      'EC6 Performance (544 л.с., 100 кВтч)':  S(servicePresets.battery_deep, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_diag, servicePresets.niopilot_cal, servicePresets.airsusp_diag, servicePresets.battery_swap, servicePresets.power_tune, servicePresets.coding, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.launch_control, servicePresets.nomi_coding, servicePresets.vmax_off),
    },
    '2 поколение (2023–2025)': {
      'EC6 (490 л.с., 75 кВтч)':               S(servicePresets.battery_diag, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU_plus, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_plus, servicePresets.niopilot_cal, servicePresets.airsusp_diag, servicePresets.airsusp_cal, servicePresets.battery_swap, servicePresets.power_tune, servicePresets.coding_premium, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.nomi_coding, servicePresets.vmax_off),
      'EC6 (490 л.с., 100 кВтч)':              S(servicePresets.battery_deep, servicePresets.battery_cal, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU_plus, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_plus, servicePresets.niopilot_cal, servicePresets.airsusp_diag, servicePresets.airsusp_cal, servicePresets.battery_swap, servicePresets.power_tune, servicePresets.coding_premium, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.launch_control, servicePresets.nomi_coding, servicePresets.vmax_off),
      'EC6 (490 л.с., 150 кВтч)':              S(servicePresets.battery_deep, servicePresets.battery_cal, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU_plus, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_plus, servicePresets.niopilot_cal, servicePresets.airsusp_diag, servicePresets.airsusp_cal, servicePresets.battery_swap, servicePresets.power_tune, servicePresets.coding_premium, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.launch_control, servicePresets.nomi_coding, servicePresets.vmax_off),
    },
    '2 поколение FL (2025–н.в.)': {
      'EC6 (490 л.с., 90 кВтч)':               S(servicePresets.battery_deep, servicePresets.battery_cal, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU_plus, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_plus, servicePresets.niopilot_cal, servicePresets.airsusp_diag, servicePresets.airsusp_cal, servicePresets.battery_swap, servicePresets.power_tune, servicePresets.coding_premium, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.launch_control, servicePresets.nomi_coding, servicePresets.vmax_off),
      'EC6 (490 л.с., 100 кВтч)':              S(servicePresets.battery_deep, servicePresets.battery_cal, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU_plus, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_plus, servicePresets.niopilot_cal, servicePresets.airsusp_diag, servicePresets.airsusp_cal, servicePresets.battery_swap, servicePresets.power_tune, servicePresets.coding_premium, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.launch_control, servicePresets.nomi_coding, servicePresets.vmax_off),
      'EC6 (490 л.с., 150 кВтч)':              S(servicePresets.battery_deep, servicePresets.battery_cal, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU_plus, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_plus, servicePresets.niopilot_cal, servicePresets.airsusp_diag, servicePresets.airsusp_cal, servicePresets.battery_swap, servicePresets.power_tune, servicePresets.coding_premium, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.launch_control, servicePresets.nomi_coding, servicePresets.vmax_off),
    },
  },

  'es7': {
    '1 поколение (2022–н.в.)': {
      'ES7 (480 л.с., 75 кВтч)':               S(servicePresets.battery_diag, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU_plus, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_plus, servicePresets.niopilot_cal, servicePresets.airsusp_diag, servicePresets.airsusp_cal, servicePresets.battery_swap, servicePresets.power_tune, servicePresets.coding_premium, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.nomi_coding, servicePresets.vmax_off),
      'ES7 (480 л.с., 100 кВтч)':              S(servicePresets.battery_deep, servicePresets.battery_cal, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU_plus, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_plus, servicePresets.niopilot_cal, servicePresets.airsusp_diag, servicePresets.airsusp_cal, servicePresets.battery_swap, servicePresets.power_tune, servicePresets.coding_premium, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.launch_control, servicePresets.nomi_coding, servicePresets.vmax_off),
      'ES7 (480 л.с., 150 кВтч)':              S(servicePresets.battery_deep, servicePresets.battery_cal, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU_plus, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_plus, servicePresets.niopilot_cal, servicePresets.airsusp_diag, servicePresets.airsusp_cal, servicePresets.battery_swap, servicePresets.power_tune, servicePresets.coding_premium, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.launch_control, servicePresets.nomi_coding, servicePresets.vmax_off),
    },
  },

  'ec7': {
    '1 поколение (2023–н.в.)': {
      'EC7 (480 л.с., 75 кВтч)':               S(servicePresets.battery_diag, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU_plus, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_plus, servicePresets.niopilot_cal, servicePresets.airsusp_diag, servicePresets.airsusp_cal, servicePresets.battery_swap, servicePresets.power_tune, servicePresets.coding_premium, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.nomi_coding, servicePresets.vmax_off),
      'EC7 (480 л.с., 100 кВтч)':              S(servicePresets.battery_deep, servicePresets.battery_cal, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU_plus, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_plus, servicePresets.niopilot_cal, servicePresets.airsusp_diag, servicePresets.airsusp_cal, servicePresets.battery_swap, servicePresets.power_tune, servicePresets.coding_premium, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.launch_control, servicePresets.nomi_coding, servicePresets.vmax_off),
      'EC7 (480 л.с., 150 кВтч)':              S(servicePresets.battery_deep, servicePresets.battery_cal, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU_plus, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_plus, servicePresets.niopilot_cal, servicePresets.airsusp_diag, servicePresets.airsusp_cal, servicePresets.battery_swap, servicePresets.power_tune, servicePresets.coding_premium, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.launch_control, servicePresets.nomi_coding, servicePresets.vmax_off),
    },
  },

  'et7': {
    '1 поколение (2022–н.в.)': {
      'ET7 (480 л.с., 75 кВтч)':               S(servicePresets.battery_diag, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU_plus, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_plus, servicePresets.niopilot_cal, servicePresets.airsusp_diag, servicePresets.airsusp_cal, servicePresets.battery_swap, servicePresets.power_tune, servicePresets.coding_premium, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.nomi_coding, servicePresets.vmax_off),
      'ET7 (480 л.с., 100 кВтч)':              S(servicePresets.battery_deep, servicePresets.battery_cal, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU_plus, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_plus, servicePresets.niopilot_cal, servicePresets.airsusp_diag, servicePresets.airsusp_cal, servicePresets.battery_swap, servicePresets.power_tune, servicePresets.coding_premium, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.launch_control, servicePresets.nomi_coding, servicePresets.vmax_off),
      'ET7 (480 л.с., 150 кВтч)':              S(servicePresets.battery_deep, servicePresets.battery_cal, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU_plus, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_plus, servicePresets.niopilot_cal, servicePresets.airsusp_diag, servicePresets.airsusp_cal, servicePresets.battery_swap, servicePresets.power_tune, servicePresets.coding_premium, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.launch_control, servicePresets.nomi_coding, servicePresets.vmax_off),
    },
  },

  'et5': {
    '1 поколение (2022–н.в.)': {
      'ET5 (490 л.с., 75 кВтч)':               S(servicePresets.battery_diag, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU_plus, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_plus, servicePresets.niopilot_cal, servicePresets.battery_swap, servicePresets.power_tune, servicePresets.coding_premium, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.nomi_coding, servicePresets.vmax_off),
      'ET5 (490 л.с., 100 кВтч)':              S(servicePresets.battery_deep, servicePresets.battery_cal, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU_plus, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_plus, servicePresets.niopilot_cal, servicePresets.battery_swap, servicePresets.power_tune, servicePresets.coding_premium, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.launch_control, servicePresets.nomi_coding, servicePresets.vmax_off),
    },
  },

  'et5t': {
    '1 поколение (2023–н.в.)': {
      'ET5T (490 л.с., 75 кВтч)':              S(servicePresets.battery_diag, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU_plus, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_plus, servicePresets.niopilot_cal, servicePresets.battery_swap, servicePresets.power_tune, servicePresets.coding_premium, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.nomi_coding, servicePresets.vmax_off),
      'ET5T (490 л.с., 100 кВтч)':             S(servicePresets.battery_deep, servicePresets.battery_cal, servicePresets.motor_dual, servicePresets.inverter_diag, servicePresets.diagECU_plus, servicePresets.charging_diag, servicePresets.cooling_diag, servicePresets.software_update, servicePresets.niopilot_plus, servicePresets.niopilot_cal, servicePresets.battery_swap, servicePresets.power_tune, servicePresets.coding_premium, servicePresets.regen_tune, servicePresets.torque_vector, servicePresets.launch_control, servicePresets.nomi_coding, servicePresets.vmax_off),
    },
  },

  'el7': {
    'см. ES7 соответствующего поколения': S(),
  },

};
