export const servicePresets = {
  diagEV:         [{ name: 'Диагностика EV системы', description: 'Полная диагностика электромобиля', price: '5 000 ₽' }],
  diagEV_plus:    [{ name: 'Диагностика EV системы', description: 'Расширенная диагностика с логами', price: '7 000 ₽' }],
  battery_hv:     [{ name: 'Диагностика HV батареи', description: 'Проверка высоковольтной батареи', price: '6 000 ₽' }],
  battery_bms:    [{ name: 'Диагностика BMS', description: 'Battery Management System', price: '5 000 ₽' }],
  battery_cal:    [{ name: 'Калибровка батареи', description: 'BMS калибровка и балансировка', price: '8 000 ₽' }],
  motor_diag:     [{ name: 'Диагностика электромоторов', description: 'Dual/Quad Motor проверка', price: '5 000 ₽' }],
  inverter_diag:  [{ name: 'Диагностика инверторов', description: 'Силовая электроника', price: '6 000 ₽' }],
  drive_unit:     [{ name: 'Диагностика Drive Unit', description: 'Приводные модули передний/задний', price: '5 500 ₽' }],
  regen_tune:     [{ name: 'Настройка рекуперации', description: 'Калибровка режимов рекуперации', price: '4 000 ₽' }],
  power_tune:     [{ name: 'Power Tune', description: 'Оптимизация характеристик мощности', price: '15 000 ₽' }],
  torque_tune:    [{ name: 'Torque Vectoring настройка', description: 'Калибровка распределения крутящего момента', price: '12 000 ₽' }],
  vmax_off:       [{ name: 'Снятие ограничения Vmax', description: 'Разблокировка максимальной скорости', price: '8 000 ₽' }],
  charge_tune:    [{ name: 'Оптимизация зарядки', description: 'Калибровка режимов зарядки DC/AC', price: '6 000 ₽' }],
  adas_diag:      [{ name: 'Диагностика ADAS', description: 'Driver+ система помощи водителю', price: '7 000 ₽' }],
  adas_cal:       [{ name: 'Калибровка ADAS', description: 'Камеры/радары/датчики', price: '10 000 ₽' }],
  air_susp:       [{ name: 'Диагностика пневмоподвески', description: 'Adaptive Air Suspension', price: '5 000 ₽' }],
  air_susp_tune:  [{ name: 'Настройка пневмоподвески', description: 'Калибровка высоты и жесткости', price: '7 000 ₽' }],
  coding:         [{ name: 'Кодирование функций', description: 'Раскодировка опций', price: '6 000 ₽' }],
  coding_adv:     [{ name: 'Расширенное кодирование', description: 'Activation скрытых функций', price: '10 000 ₽' }],
  soft_update:    [{ name: 'Обновление ПО', description: 'Software update всех модулей', price: '8 000 ₽' }],
  camp_mode:      [{ name: 'Активация Camp Mode', description: 'Режим кемпинга и Pet Mode', price: '3 000 ₽' }],
  tank_turn:      [{ name: 'Активация Tank Turn', description: 'Quad Motor разворот на месте', price: '5 000 ₽' }],
  off_road:       [{ name: 'Off-Road режимы', description: 'Активация внедорожных режимов', price: '7 000 ₽' }],
  dtc_off:        [{ name: 'Отключение DTC', description: 'Удаление кодов ошибок', price: '4 000 ₽' }],
  gear_guard:     [{ name: 'Настройка Gear Guard', description: 'Система охраны и камер', price: '5 000 ₽' }],
};

const S = (...sets) => sets.flat();

export const rivianData = {

  'r1t': {
    '1 поколение дорест (2021–2023)': {
      'Launch Edition Quad Motor 135 kWh':  S(servicePresets.diagEV_plus, servicePresets.battery_hv, servicePresets.battery_bms, servicePresets.motor_diag, servicePresets.inverter_diag, servicePresets.drive_unit, servicePresets.power_tune, servicePresets.torque_tune, servicePresets.tank_turn, servicePresets.vmax_off, servicePresets.adas_diag, servicePresets.air_susp, servicePresets.coding_adv, servicePresets.off_road, servicePresets.gear_guard),
      'Adventure Quad Motor 135 kWh':       S(servicePresets.diagEV, servicePresets.battery_hv, servicePresets.battery_bms, servicePresets.motor_diag, servicePresets.inverter_diag, servicePresets.drive_unit, servicePresets.power_tune, servicePresets.torque_tune, servicePresets.tank_turn, servicePresets.vmax_off, servicePresets.adas_diag, servicePresets.air_susp, servicePresets.coding, servicePresets.off_road, servicePresets.gear_guard),
      'Adventure Dual Motor 135 kWh':       S(servicePresets.diagEV, servicePresets.battery_hv, servicePresets.battery_bms, servicePresets.motor_diag, servicePresets.inverter_diag, servicePresets.drive_unit, servicePresets.power_tune, servicePresets.regen_tune, servicePresets.vmax_off, servicePresets.adas_diag, servicePresets.air_susp, servicePresets.coding, servicePresets.off_road, servicePresets.gear_guard),
    },
    '1 поколение FL (2023–2024)': {
      'Adventure Quad Motor 135 kWh':       S(servicePresets.diagEV, servicePresets.battery_hv, servicePresets.battery_bms, servicePresets.motor_diag, servicePresets.inverter_diag, servicePresets.drive_unit, servicePresets.power_tune, servicePresets.torque_tune, servicePresets.tank_turn, servicePresets.vmax_off, servicePresets.adas_diag, servicePresets.adas_cal, servicePresets.air_susp, servicePresets.air_susp_tune, servicePresets.coding, servicePresets.off_road, servicePresets.gear_guard),
      'Adventure Dual Motor 135 kWh':       S(servicePresets.diagEV, servicePresets.battery_hv, servicePresets.battery_bms, servicePresets.motor_diag, servicePresets.inverter_diag, servicePresets.drive_unit, servicePresets.power_tune, servicePresets.regen_tune, servicePresets.vmax_off, servicePresets.adas_diag, servicePresets.adas_cal, servicePresets.air_susp, servicePresets.air_susp_tune, servicePresets.coding, servicePresets.off_road, servicePresets.gear_guard),
      'Adventure Quad Motor Max 180 kWh':   S(servicePresets.diagEV_plus, servicePresets.battery_hv, servicePresets.battery_bms, servicePresets.battery_cal, servicePresets.motor_diag, servicePresets.inverter_diag, servicePresets.drive_unit, servicePresets.power_tune, servicePresets.torque_tune, servicePresets.tank_turn, servicePresets.charge_tune, servicePresets.vmax_off, servicePresets.adas_diag, servicePresets.adas_cal, servicePresets.air_susp, servicePresets.air_susp_tune, servicePresets.coding_adv, servicePresets.off_road, servicePresets.gear_guard),
      'Adventure Dual Motor Max 180 kWh':   S(servicePresets.diagEV_plus, servicePresets.battery_hv, servicePresets.battery_bms, servicePresets.battery_cal, servicePresets.motor_diag, servicePresets.inverter_diag, servicePresets.drive_unit, servicePresets.power_tune, servicePresets.regen_tune, servicePresets.charge_tune, servicePresets.vmax_off, servicePresets.adas_diag, servicePresets.adas_cal, servicePresets.air_susp, servicePresets.air_susp_tune, servicePresets.coding_adv, servicePresets.off_road, servicePresets.gear_guard),
      'Adventure Dual Motor Standard 106 kWh': S(servicePresets.diagEV, servicePresets.battery_hv, servicePresets.battery_bms, servicePresets.motor_diag, servicePresets.inverter_diag, servicePresets.drive_unit, servicePresets.power_tune, servicePresets.regen_tune, servicePresets.vmax_off, servicePresets.adas_diag, servicePresets.air_susp, servicePresets.coding, servicePresets.off_road, servicePresets.gear_guard),
      'Adventure Dual Motor Standard+ 121 kWh': S(servicePresets.diagEV, servicePresets.battery_hv, servicePresets.battery_bms, servicePresets.motor_diag, servicePresets.inverter_diag, servicePresets.drive_unit, servicePresets.power_tune, servicePresets.regen_tune, servicePresets.vmax_off, servicePresets.adas_diag, servicePresets.air_susp, servicePresets.coding, servicePresets.off_road, servicePresets.gear_guard),
    },
    '2 поколение (2025–н.в.)': {
      'Dual Motor Standard+ 121 kWh':       S(servicePresets.diagEV, servicePresets.battery_hv, servicePresets.battery_bms, servicePresets.motor_diag, servicePresets.inverter_diag, servicePresets.drive_unit, servicePresets.power_tune, servicePresets.regen_tune, servicePresets.vmax_off, servicePresets.adas_diag, servicePresets.adas_cal, servicePresets.air_susp, servicePresets.air_susp_tune, servicePresets.coding, servicePresets.soft_update, servicePresets.off_road, servicePresets.gear_guard),
      'Dual Motor Large 135 kWh':           S(servicePresets.diagEV, servicePresets.battery_hv, servicePresets.battery_bms, servicePresets.motor_diag, servicePresets.inverter_diag, servicePresets.drive_unit, servicePresets.power_tune, servicePresets.regen_tune, servicePresets.vmax_off, servicePresets.adas_diag, servicePresets.adas_cal, servicePresets.air_susp, servicePresets.air_susp_tune, servicePresets.coding, servicePresets.soft_update, servicePresets.off_road, servicePresets.gear_guard),
      'Quad Motor Large 135 kWh':           S(servicePresets.diagEV_plus, servicePresets.battery_hv, servicePresets.battery_bms, servicePresets.motor_diag, servicePresets.inverter_diag, servicePresets.drive_unit, servicePresets.power_tune, servicePresets.torque_tune, servicePresets.tank_turn, servicePresets.vmax_off, servicePresets.adas_diag, servicePresets.adas_cal, servicePresets.air_susp, servicePresets.air_susp_tune, servicePresets.coding_adv, servicePresets.soft_update, servicePresets.off_road, servicePresets.gear_guard),
      'Tri Motor Max 180 kWh':              S(servicePresets.diagEV_plus, servicePresets.battery_hv, servicePresets.battery_bms, servicePresets.battery_cal, servicePresets.motor_diag, servicePresets.inverter_diag, servicePresets.drive_unit, servicePresets.power_tune, servicePresets.torque_tune, servicePresets.charge_tune, servicePresets.vmax_off, servicePresets.adas_diag, servicePresets.adas_cal, servicePresets.air_susp, servicePresets.air_susp_tune, servicePresets.coding_adv, servicePresets.soft_update, servicePresets.off_road, servicePresets.gear_guard),
      'Quad Motor Max 180 kWh':             S(servicePresets.diagEV_plus, servicePresets.battery_hv, servicePresets.battery_bms, servicePresets.battery_cal, servicePresets.motor_diag, servicePresets.inverter_diag, servicePresets.drive_unit, servicePresets.power_tune, servicePresets.torque_tune, servicePresets.tank_turn, servicePresets.charge_tune, servicePresets.vmax_off, servicePresets.adas_diag, servicePresets.adas_cal, servicePresets.air_susp, servicePresets.air_susp_tune, servicePresets.coding_adv, servicePresets.soft_update, servicePresets.off_road, servicePresets.gear_guard),
    },
  },

  'r1s': {
    '1 поколение дорест (2022–2023)': {
      'Launch Edition Quad Motor 135 kWh':  S(servicePresets.diagEV_plus, servicePresets.battery_hv, servicePresets.battery_bms, servicePresets.motor_diag, servicePresets.inverter_diag, servicePresets.drive_unit, servicePresets.power_tune, servicePresets.torque_tune, servicePresets.tank_turn, servicePresets.vmax_off, servicePresets.adas_diag, servicePresets.air_susp, servicePresets.coding_adv, servicePresets.off_road, servicePresets.gear_guard),
      'Adventure Quad Motor 135 kWh':       S(servicePresets.diagEV, servicePresets.battery_hv, servicePresets.battery_bms, servicePresets.motor_diag, servicePresets.inverter_diag, servicePresets.drive_unit, servicePresets.power_tune, servicePresets.torque_tune, servicePresets.tank_turn, servicePresets.vmax_off, servicePresets.adas_diag, servicePresets.air_susp, servicePresets.coding, servicePresets.off_road, servicePresets.gear_guard),
      'Adventure Dual Motor 135 kWh':       S(servicePresets.diagEV, servicePresets.battery_hv, servicePresets.battery_bms, servicePresets.motor_diag, servicePresets.inverter_diag, servicePresets.drive_unit, servicePresets.power_tune, servicePresets.regen_tune, servicePresets.vmax_off, servicePresets.adas_diag, servicePresets.air_susp, servicePresets.coding, servicePresets.off_road, servicePresets.gear_guard),
    },
    '1 поколение FL (2023–2024)': {
      'Adventure Quad Motor 135 kWh':       S(servicePresets.diagEV, servicePresets.battery_hv, servicePresets.battery_bms, servicePresets.motor_diag, servicePresets.inverter_diag, servicePresets.drive_unit, servicePresets.power_tune, servicePresets.torque_tune, servicePresets.tank_turn, servicePresets.vmax_off, servicePresets.adas_diag, servicePresets.adas_cal, servicePresets.air_susp, servicePresets.air_susp_tune, servicePresets.coding, servicePresets.off_road, servicePresets.gear_guard),
      'Adventure Dual Motor 135 kWh':       S(servicePresets.diagEV, servicePresets.battery_hv, servicePresets.battery_bms, servicePresets.motor_diag, servicePresets.inverter_diag, servicePresets.drive_unit, servicePresets.power_tune, servicePresets.regen_tune, servicePresets.vmax_off, servicePresets.adas_diag, servicePresets.adas_cal, servicePresets.air_susp, servicePresets.air_susp_tune, servicePresets.coding, servicePresets.off_road, servicePresets.gear_guard),
      'Adventure Quad Motor Max 180 kWh':   S(servicePresets.diagEV_plus, servicePresets.battery_hv, servicePresets.battery_bms, servicePresets.battery_cal, servicePresets.motor_diag, servicePresets.inverter_diag, servicePresets.drive_unit, servicePresets.power_tune, servicePresets.torque_tune, servicePresets.tank_turn, servicePresets.charge_tune, servicePresets.vmax_off, servicePresets.adas_diag, servicePresets.adas_cal, servicePresets.air_susp, servicePresets.air_susp_tune, servicePresets.coding_adv, servicePresets.off_road, servicePresets.gear_guard),
      'Adventure Dual Motor Max 180 kWh':   S(servicePresets.diagEV_plus, servicePresets.battery_hv, servicePresets.battery_bms, servicePresets.battery_cal, servicePresets.motor_diag, servicePresets.inverter_diag, servicePresets.drive_unit, servicePresets.power_tune, servicePresets.regen_tune, servicePresets.charge_tune, servicePresets.vmax_off, servicePresets.adas_diag, servicePresets.adas_cal, servicePresets.air_susp, servicePresets.air_susp_tune, servicePresets.coding_adv, servicePresets.off_road, servicePresets.gear_guard),
      'Adventure Dual Motor Standard 106 kWh': S(servicePresets.diagEV, servicePresets.battery_hv, servicePresets.battery_bms, servicePresets.motor_diag, servicePresets.inverter_diag, servicePresets.drive_unit, servicePresets.power_tune, servicePresets.regen_tune, servicePresets.vmax_off, servicePresets.adas_diag, servicePresets.air_susp, servicePresets.coding, servicePresets.off_road, servicePresets.gear_guard),
      'Adventure Dual Motor Standard+ 121 kWh': S(servicePresets.diagEV, servicePresets.battery_hv, servicePresets.battery_bms, servicePresets.motor_diag, servicePresets.inverter_diag, servicePresets.drive_unit, servicePresets.power_tune, servicePresets.regen_tune, servicePresets.vmax_off, servicePresets.adas_diag, servicePresets.air_susp, servicePresets.coding, servicePresets.off_road, servicePresets.gear_guard),
    },
    '2 поколение (2025–н.в.)': {
      'Dual Motor Standard+ 121 kWh':       S(servicePresets.diagEV, servicePresets.battery_hv, servicePresets.battery_bms, servicePresets.motor_diag, servicePresets.inverter_diag, servicePresets.drive_unit, servicePresets.power_tune, servicePresets.regen_tune, servicePresets.vmax_off, servicePresets.adas_diag, servicePresets.adas_cal, servicePresets.air_susp, servicePresets.air_susp_tune, servicePresets.coding, servicePresets.soft_update, servicePresets.off_road, servicePresets.gear_guard, servicePresets.camp_mode),
      'Dual Motor Large 135 kWh':           S(servicePresets.diagEV, servicePresets.battery_hv, servicePresets.battery_bms, servicePresets.motor_diag, servicePresets.inverter_diag, servicePresets.drive_unit, servicePresets.power_tune, servicePresets.regen_tune, servicePresets.vmax_off, servicePresets.adas_diag, servicePresets.adas_cal, servicePresets.air_susp, servicePresets.air_susp_tune, servicePresets.coding, servicePresets.soft_update, servicePresets.off_road, servicePresets.gear_guard, servicePresets.camp_mode),
      'Quad Motor Large 135 kWh':           S(servicePresets.diagEV_plus, servicePresets.battery_hv, servicePresets.battery_bms, servicePresets.motor_diag, servicePresets.inverter_diag, servicePresets.drive_unit, servicePresets.power_tune, servicePresets.torque_tune, servicePresets.tank_turn, servicePresets.vmax_off, servicePresets.adas_diag, servicePresets.adas_cal, servicePresets.air_susp, servicePresets.air_susp_tune, servicePresets.coding_adv, servicePresets.soft_update, servicePresets.off_road, servicePresets.gear_guard, servicePresets.camp_mode),
      'Tri Motor Max 180 kWh':              S(servicePresets.diagEV_plus, servicePresets.battery_hv, servicePresets.battery_bms, servicePresets.battery_cal, servicePresets.motor_diag, servicePresets.inverter_diag, servicePresets.drive_unit, servicePresets.power_tune, servicePresets.torque_tune, servicePresets.charge_tune, servicePresets.vmax_off, servicePresets.adas_diag, servicePresets.adas_cal, servicePresets.air_susp, servicePresets.air_susp_tune, servicePresets.coding_adv, servicePresets.soft_update, servicePresets.off_road, servicePresets.gear_guard, servicePresets.camp_mode),
      'Quad Motor Max 180 kWh':             S(servicePresets.diagEV_plus, servicePresets.battery_hv, servicePresets.battery_bms, servicePresets.battery_cal, servicePresets.motor_diag, servicePresets.inverter_diag, servicePresets.drive_unit, servicePresets.power_tune, servicePresets.torque_tune, servicePresets.tank_turn, servicePresets.charge_tune, servicePresets.vmax_off, servicePresets.adas_diag, servicePresets.adas_cal, servicePresets.air_susp, servicePresets.air_susp_tune, servicePresets.coding_adv, servicePresets.soft_update, servicePresets.off_road, servicePresets.gear_guard, servicePresets.camp_mode),
    },
  },

};
